repos:
  - repo: https://github.com/kjaymiller/pin-versions
    rev: 2026.3.4
    hooks:
      - id: pin-versions
        name: pin-versions
        description: Check that all dependencies in pyproject.toml are pinned to a version
        language: python
        entry: pin-versions
        files: pyproject\.toml$
        pass_filenames: false
