- id: pin-versions
  name: pin-versions
  description: Check that all dependencies in pyproject.toml are pinned to a version
  entry: pin-versions
  language: python
  files: pyproject\.toml$
  pass_filenames: false
